volumes:
  pg_data:
  static:

services:
  db:
    image: postgres:13
    env_file: .env
    volumes:
      - pg_data:/var/lib/postgresql/data
  backend:
    image: zmarik/taski_backend:latest
    env_file: .env
    volumes:
      - static:/backend_static

  frontend:
    env_file: .env
    image: zmarik/taski_frontend:latest
    command: cp -r /app/build/. /frontend_static/
    volumes:
      - static:/frontend_static

  gateway:
    image: zmarik/taski_gateway:latest
    env_file: .env
    volumes:
      - static:/staticfiles
    ports:
      - 8000:80