# Создать образ на основе базового слоя,
# который содержит файлы ОС и интерпретатор Python 3.12.
FROM python:3.11

# Переходим в образе в директорию /app: в ней будем хранить код проекта.
# Если директории с указанным именем нет, она будет создана. 
# Название директории может быть любым.
WORKDIR /app

# Creating needed dirs
RUN mkdir /data/
RUN mkdir /backend_static/ &&  mkdir /backend_static/static/
# Дальнейшие инструкции будут выполняться в директории /app

# Скопировать с локального компьютера файл зависимостей
# в текущую директорию (текущая директория — это /app).
COPY requirements.txt .

# Выполнить в текущей директории команду терминала
# для установки зависимостей.
RUN pip install -r requirements.txt --no-cache-dir

RUN pip install gunicorn==23.0.0 

# Скопировать всё необходимое содержимое 
# той директории локального компьютера, где сохранён Dockerfile,
# в текущую рабочую директорию образа — /app.
COPY . .

# Python related commands
RUN python manage.py migrate
RUN python manage.py collectstatic
RUN cp -r /app/collected_static/. /backend_static/static/ 

# При старте контейнера запустить сервер разработки.
CMD ["gunicorn", "--bind", "0.0.0.0:8000", "backend.wsgi"]